const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("Event contract", function () {
  it("Should print event called log", async function () {
    const Event = await ethers.getContractFactory("Event");
    const contract = await Event.deploy();

    //     var abi = /* abi as generated by the compiler */;
    // var ClientReceipt = web3.eth.contract(abi);
    // var clientReceipt = ClientReceipt.at("0x1234...ab67" /* address */);

    //TODO
    // TypeError: contract.Transfer is not a function
    // var transferEvent = contract.Transfer();

    // watch for changes
    // transferEvent.watch(function (error, result) {
    //   // result contains non-indexed arguments and topics
    //   // given to the `Deposit` call.
    //   if (!error)
    //     console.log(result);
    // });

  });
});